### ISSUE TITLE
footer example doesn't add horizontal rule, mute font

### ISSUE THREAD

**Issue by zachvalenta** [kognise/water.css#160]
The footer recently added to the demo page https://github.com/kognise/water.css/pull/122 doesn't seem to work for me re: adding horizontal rule above footer and muting font.

Here's what I'm seeing:

![Screen Shot 2019-11-08 at 11 45 52 AM](https://user-images.githubusercontent.com/11388735/68495021-6335d180-021d-11ea-8392-7eee22c337b5.png)

And here's my markup:

```html
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Test Runner Server</title>
    <link rel='stylesheet' href='https://cdn.jsdelivr.net/gh/kognise/water.css@latest/dist/dark.css'>
</head>

<body>

    <h2>jobs</h2>

    <table>
        <thead>
            <tr>
                <th>id</th>
                <th>text</th>
            </tr>
        </thead>
        <tbody>
            {% for thing in things %}
            <tr>
                <td>{{ thing.id }}</td>
                <td>{{ thing.text }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <footer>
            Here is an example of a footer! Maybe you want to put some links here. <a href='#'>Privacy Policy</a> | <a href='https://github.com/kognise/water.css'>Contribute</a>
    </footer>

</body>
```

**Comment by kylejrp** [comment]
I think this is because we haven't created a new release yet. We're working on releasing a version 2.0.0 on npm with the latest additions. 

I'll confirm when I'm at my computer again.

Sorry for the inconvenience!

**Comment by zachvalenta** [comment]
Cool, looking forward to it and thanks for the help :) 👍🏼

**Comment by pierluigi** [comment]
Any updates? Thanks!

**Comment by kognise** [comment]
This has been fixed in 2.0 🚀

**Comment by zachvalenta** [comment]
I'm still getting the same behavior from 2.0; not sure if I'm making some dumb obvious mistake though.

This html (copied the footer markup from the [example site](https://watercss.netlify.app/)) :

```html
<head>
    <link rel='stylesheet' href='https://cdn.jsdelivr.net/gh/kognise/water.css@latest/dist/dark.css'>
</head>

<body>
    <div>main content</div>
    <footer>
        Here is an example of a footer! Maybe you want to put some links here. <a href="#">Privacy Policy</a> | <a href="https://github.com/kognise/water.css">Contribute</a>
    </footer>
</body>
```

is rendered like this:

![Screen Shot 2020-05-30 at 6 10 56 PM](https://user-images.githubusercontent.com/11388735/83339957-f1000980-a2a0-11ea-95e6-796610ccbbea.png)

**Comment by jonaskuske** [comment]
2.0 isn't published yet (we're working on it!), so `water.css@latest` still gives you the old styles. You can subscribe to "Releases only" for this repository if you wan't to be notified when 2.0 is published. :)

![image](https://user-images.githubusercontent.com/30421456/83340151-02fb9f80-a2d5-11ea-8965-4a781747f775.png)

**Comment by zachvalenta** [comment]
> so water.css@latest still gives you the old styles

Confused how 'latest' is also simultaneously 'old'. 

IMO more clear to close issue once work is actually merged but just my two cents.

**Comment by kognise** [comment]
> Confused how 'latest' is also simultaneously 'old'.
We haven't published 2.0 yet, and latest refers to the latest published release.

**Comment by jonaskuske** [comment]
> IMO more clear to close issue once work is actually merged but just my two cents.

You're absolutely right. Only closing issues once they're on master, and making sure that master is published regularly so it's always matching the latest published version is the way to do things – and we'll have that once 2.0 is live!  
For now, closing issues that we already addressed in our 2.0 branch helps us with housekeeping and publishing 2.0 faster. 👍🏻

**Comment by zachvalenta** [comment]
Fair point as well. Realize you guys are putting a lot of work in to make 2.0 happen and I (and all the other happy users) appreciate it. Keep up the good work.
